// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmd

import (
	"time"
)

const TableNameBtCollector = "bt_collector"

// BtCollector mapped from table <bt_collector>
type BtCollector struct {
	ID              int64     `gorm:"column:id;primaryKey" json:"id"`
	CollectorTypeID int64     `gorm:"column:collector_type_id;not null" json:"collector_type_id"`
	Name            string    `gorm:"column:name" json:"name"`
	Description     string    `gorm:"column:description" json:"description"`
	DelYn           string    `gorm:"column:del_yn;default:N" json:"del_yn"`
	RegDt           time.Time `gorm:"column:reg_dt;default:current_timestamp()" json:"reg_dt"`
	ModDt           time.Time `gorm:"column:mod_dt" json:"mod_dt"`
	DelDt           time.Time `gorm:"column:del_dt" json:"del_dt"`
}

// TableName BtCollector's table name
func (*BtCollector) TableName() string {
	return TableNameBtCollector
}
