// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmd

import (
	"time"
)

const TableNameBtCollectorProvider = "bt_collector_provider"

// BtCollectorProvider mapped from table <bt_collector_provider>
type BtCollectorProvider struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CollectorID int64     `gorm:"column:collector_id;not null" json:"collector_id"`
	ProviderID  int64     `gorm:"column:provider_id;not null" json:"provider_id"`
	RegDt       time.Time `gorm:"column:reg_dt;default:current_timestamp()" json:"reg_dt"`
}

// TableName BtCollectorProvider's table name
func (*BtCollectorProvider) TableName() string {
	return TableNameBtCollectorProvider
}
