// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmd

import "time"

// BtModule mapped from table <bt_module>
type BtModule struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProviderID   int64     `gorm:"column:provider_id;not null" json:"provider_id"`
	ModuleTypeID int64     `gorm:"column:module_type_id;not null" json:"module_type_id"`
	Name         string    `gorm:"column:name" json:"name"`
	Description  string    `gorm:"column:description" json:"description"`
	DelYn        string    `gorm:"column:del_yn;not null;default:'N'::character varying" json:"del_yn"`
	RegDt        time.Time `gorm:"column:reg_dt;default:now()" json:"reg_dt"`
	ModDt        time.Time `gorm:"column:mod_dt" json:"mod_dt"`
	DelDt        time.Time `gorm:"column:del_dt" json:"del_dt"`
}

// TableName BtModule's table name
func (*BtModule) TableName() string {
	return "bt_module"
}
