// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmd

import (
	"time"
)

const TableNameBtProvider = "bt_provider"

// BtProvider mapped from table <bt_provider>
type BtProvider struct {
	ID             int64     `gorm:"column:id;primaryKey" json:"id"`
	ProviderTypeID int64     `gorm:"column:provider_type_id;not null" json:"provider_type_id"`
	Name           string    `gorm:"column:name" json:"name"`
	Description    string    `gorm:"column:description" json:"description"`
	DelYn          string    `gorm:"column:del_yn;default:N" json:"del_yn"`
	RegDt          time.Time `gorm:"column:reg_dt;default:current_timestamp()" json:"reg_dt"`
	ModDt          time.Time `gorm:"column:mod_dt" json:"mod_dt"`
	DelDt          time.Time `gorm:"column:del_dt" json:"del_dt"`
	UUID           string    `gorm:"column:uuid" json:"uuid"`
}

// TableName BtProvider's table name
func (*BtProvider) TableName() string {
	return TableNameBtProvider
}
